### ISSUE TITLE
Not-Emesson-Bot Issue

### ISSUE THREAD

**Issue by pton4** [Kizuno18/simple-otserv-account-creator#2]
Hi there,

I am contacting you because I am experimenting some issues with the Twitch Ad Bot you published. I will send some screenshoots with the configuration & errors I am getting.
I would appreciate a lot your help 🙏

![screen 1](https://github.com/Kizuno18/TibiaAccMaker-website-/assets/124053728/c3fded16-3244-4ff2-9bac-ca61698d883b)
![screen 2](https://github.com/Kizuno18/TibiaAccMaker-website-/assets/124053728/2de1d05d-84d7-4081-8c79-94570ccbf056)
![screen 3](https://github.com/Kizuno18/TibiaAccMaker-website-/assets/124053728/85c31270-d373-4b10-a2d7-705be8aa60e8)
![screen 4](https://github.com/Kizuno18/TibiaAccMaker-website-/assets/124053728/3f559ed8-56d9-44d4-b3e4-6ac89f6c6f76)

**Comment by Kizuno18** [comment]
It is outdated
Feel free to contact me in discord: kizuno18
